# .github/workflows/test.yml
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    # バックエンドのテスト
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci

    - name: Run Prisma migrations
      working-directory: ./backend
      run: |
        npx prisma migrate deploy
        npx prisma generate
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

    # フロントエンドのテスト
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test

    # E2Eテスト
    - name: Install Cypress
      working-directory: ./frontend
      run: npm install cypress

    - name: Run E2E tests
      working-directory: ./frontend
      run: |
        npm run dev & # フロントエンドサーバーを起動
        cd ../backend && npm run dev & # バックエンドサーバーを起動
        wait-on http://localhost:3000 http://localhost:4001
        cd ../frontend && npm run cypress:run
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        JWT_SECRET: test-secret